default: &default
  adapter: postgresql
  encoding: unicode
  username: contractually
  password: test
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5


development:
  <<: *default
  database: contractually

test:
  <<: *default
  adapter: sqlite3
  database: contractually_test

secondbase:
  development:
    <<: *default
    database: shared
    host: shared.cirjgw1iubqm.us-west-2.rds.amazonaws.com
    username: bunge
    port: 5432
    password: CORPSHARED