# Oracle/OCI 8i, 9, 10g
#
# Requires Ruby/OCI8:
#  https://github.com/kubo/ruby-oci8
#
# Specify your database using any valid connection syntax, such as a
# tnsnames.ora service name, or an SQL connect string of the form:
#
#   //host:[port][/service name]
#
# By default prefetch_rows (OCI_ATTR_PREFETCH_ROWS) is set to 100. And
# until true bind variables are supported, cursor_sharing is set by default
# to 'similar'. Both can be changed in the configuration below the defaults
# are equivalent to specifying:
#
#  prefetch_rows: 100
#  cursor_sharing: similar
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: contractually
  password: test
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

# development: 
#   adapter: oracle_enhanced 
#   database: <IP>/<SID> 
#   username: ruby 
#   password: ruby

development:
  <<: *default
  database: compliance_dev

# development:
#   <<: *default
#   database: dev
#   username: ebroot
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: localhost
#   port: <%= ENV['RDS_PORT'] %>

# development:
#   <<: *default
#   adapter: sqlite3
#   jndi: jdbc/sqlite3
#   database: compliance_dev.sqlite3
#   url: "jdbc:sqlite3://C:/Sites/compliance/compliance_dev.sqlite3"
#   driver: org.apache.hadoop.hive.jdbc.HiveDriver

# development:
#   <<: *default
#   database: <%= ENV['RDS_DB_NAME'] %>
#   username: <%= ENV['RDS_USERNAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOSTNAME'] %>
#   port: <%= ENV['RDS_PORT'] %>


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  adapter: sqlite3
  database: compliance_test

# development:
#   <<: *default
#   adapter: sqlite3
#   database: C:/Sites/compliance/compliance_dev.sqlite3

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="oracle://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
# production:
#   <<: *default
#   database: <%= ENV['RDS_DB_NAME'] %>
#   username: <%= ENV['RDS_USERNAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOSTNAME'] %>
#   port: <%= ENV['RDS_PORT'] %>